### ISSUE TITLE
Error on transfering

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/kloud51#1]
The domain you entered is not valid. Enter only the part after the www. and include the TLD

**Comment by Alir3z4** [comment]
http://www.webhostingtalk.com/showthread.php?t=1209763

**Comment by Alir3z4** [comment]
http://forum.whmcs.com/showthread.php?48381-Please-help-%28The-domain-you-entered-is-not-valid%29

**Comment by Alir3z4** [comment]
I think this is done by now and version 6 has fixed it, right ?

**Comment by AmirSavand** [comment]
I don't get this :/

**Comment by Alir3z4** [comment]
No worries.
We would get an error on transferring a domain to us.

It has been fixed.
