### ISSUE TITLE
Add control panels logo to VPS plan page

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/kloud51#3]

**Comment by Alir3z4** [comment]
close it if it's done?

**Comment by AmirSavand** [comment]
What's this: 

![image](https://cloud.githubusercontent.com/assets/4629328/9721170/234f1eb8-55a7-11e5-9748-4b365b01ab97.png)

**Comment by Alir3z4** [comment]
Cool, cool!
It's great.

Close the issue then please.

**Comment by Alir3z4** [comment]
close this @amirm3hdi  ?

**Comment by AmirSavand** [comment]
Yea DUH
