### ISSUE TITLE
Remove language choose input from the header

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/kloud51#4]

**Comment by Alir3z4** [comment]
Is this done ?

**Comment by AmirSavand** [comment]
Should I move it to footer or remove it prem ?

**Comment by Alir3z4** [comment]
It's not useful since our content are not translated in the CMS.
But the other part of websites are translated already.

I guess, just let it be there and don't move it.

**Comment by Alir3z4** [comment]
The issue is closed now.
