### ISSUE TITLE
Eye candy python,ruby support

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/kloud51#5]
with their framework and stuff on the home page

**Comment by Alir3z4** [comment]
just put up some logos and stuff about them.
pictures are much better to show off these things.

stuff like that,

**Comment by AmirSavand** [comment]
Check this out, I can also make them equal heights (with a little bit of JS)

![image](https://cloud.githubusercontent.com/assets/4629328/9721038/cf13c4a8-55a5-11e5-8b7f-e2353761b4dc.png)

**Comment by Alir3z4** [comment]
Awesome!

**Comment by Alir3z4** [comment]
Although still I don't see any framework logo and icon :D

**Comment by AmirSavand** [comment]
And where should I put them?

**Comment by Alir3z4** [comment]
Anywhere that you think it will make the website much beautiful.
This features are specific for cPanel (linux web hosting)

**Comment by Alir3z4** [comment]
Still this one is not done ? why why why whaaaaaaay ?

**Comment by Alir3z4** [comment]
Bump bump ?

**Comment by Alir3z4** [comment]
Should I still bump bump this issue ?

**Comment by AmirSavand** [comment]
Send me an example of a framework ICON... and Where to put'em

**Comment by Alir3z4** [comment]
@amirm3hdi Years later and ?
