### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/kloud51#56]

**Comment by AmirSavand** [comment]
We don't have translation for kloud51.com either. But that can be done.

We redirect logged in users to billing (except from landing page), so user will spend 99% of the time on whmcs.

We can have translation too, but this repo is mostly hosting pages.

**Comment by Alir3z4** [comment]
Yep, the hosting pages and their info should be translatable.
We need the translation for at least 2 languages, English and Russian.

For an example you can have a look at
https://github.com/popcorn-official/popcorn-site/blob/master/server.js

**Comment by AmirSavand** [comment]
Not needed now. Reopen later.
