### ISSUE TITLE
Deploy to kloud51.com

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/kloud51#59]
@Alir3z4 it's ready.

- [ ] Deploy to kloud51.com
- [x] Choose a name for subdomain.
- [ ] Use dash.kloud51.com for the whmcs app.
- [ ] Use default whmcs template (not stack).

**Comment by Alir3z4** [comment]
From the list below, which one would you prefer for WHMCS ?

* billing
* console
* dash
* dashboard

**Comment by AmirSavand** [comment]
@Alir3z4 dash would be good, shortest and makes more sense.
