### ISSUE TITLE
Eye candy promotion code on the home page

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/kloud51#6]
The promotion code is simple and doesn't pop into the eyes well.
Could you make it more fancy and fun and cool and nice and stuff like that with a little bit of  rock'n roll involved ?

**Comment by AmirSavand** [comment]
I'll see what I can do

On 9/7/2015 1:32 PM, Alireza Savand wrote:

> The promotion code is simple and doesn't pop into the eyes well.
> Could you make it more fancy and fun and cool and nice and stuff like 
> that with a little bit of rock'n roll involved ?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/SavandBros/www.kloud51.com/issues/6.

---

This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
