### ISSUE TITLE
Why Kloud51? 

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/kloud51#7]
In the front page, change the word from "Quality Hosting" to "Awesome Hosting " or "Amazing Hosting" or "Premium Hosting".

_note: I mean I could do it by myself by going to CMS but I'd like you to do it :D_

**Comment by AmirSavand** [comment]
***\* you, In other words, CONSIDER IT DONE

On 9/7/2015 4:33 PM, Alireza Savand wrote:

> In the front page, change the word from "Quality Hosting" to "Awesome 
> Hosting " or "Amazing Hosting" or "Premium Hosting".
> 
> /note: I mean I could do it by myself by going to CMS but I'd like you 
> to do it :D/
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/SavandBros/www.kloud51.com/issues/7.

---

This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Alir3z4** [comment]
Lol. Thanks.
Close the issue when it's done please.

**Comment by AmirSavand** [comment]
Done.

**Comment by Alir3z4** [comment]
Great!
