### ISSUE TITLE
Different icons for Linux web hosting packages

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/kloud51#8]
@amirm3hdi Should we have different icons for each Linux web hosting packages ?

My opinion would be just remove all the icons from the linux plans and let it be just Windows plans.

what do you think ?

**Comment by AmirSavand** [comment]
I'll try to remove icons and make them Tables.

**Comment by Alir3z4** [comment]
bump bump!

**Comment by AmirSavand** [comment]
You need to close these issues, Homepage is fine... wanna make it like 
kindergarten?

**Comment by Alir3z4** [comment]
We still have those icons, we were talking about removing icons

**Comment by Alir3z4** [comment]
Wow, oh my god
Finally!

**Comment by AmirSavand** [comment]
The thing is i didn't know what Icons you were talking about.
