### ISSUE TITLE
Enhance home page with Hosting plans and and neat features

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/kloud51#81]

**Comment by AmirSavand** [comment]
Explain a bit more please.

**Comment by Alir3z4** [comment]
Make a super power page

**Comment by Alir3z4** [comment]
Make a cache machine

**Comment by AmirSavand** [comment]
@Alir3z4 have you seen the other tasks for homepage? Screenshots of member area for example.

**Comment by Alir3z4** [comment]
I have not, I'm hoping they all gonna bring candies to the home page
