### ISSUE TITLE
Web Hosting page needs more love

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/kloud51#85]
I think web hosting pages needs more enhancement, this page will be visited more often that other hosting pages.

* Compare table
* Technical specs:
  * Number of databases, ftp, emails, websites, domains, subdomains, etc for each plan
  * EP/Concurrent Connections
  * Panel type = cPanel
  * Backups = Daily (Free of charge)
  * Supporting PHP (5.5, 5.6, 7.0. 7.01), Python (2, 3), Ruby, Perl
  * SSH Access
  * FREE SSL for GOD SAKE
  * etc...
* Add more features to "Main Features" section. You can use stuff mentioned above as well.

**Comment by AmirSavand** [comment]
Updated.
