### ISSUE TITLE
Remove Windows Web Hosting stuff

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/kloud51#9]
@amirm3hdi Remove all the content related to windows on the main page and also un-publish `/windows-web-hosting` page in CMS.

This should be done ASAP.

**Comment by Alir3z4** [comment]
@amirm3hdi I'm waiting on this.

**Comment by AmirSavand** [comment]
Removed the LINKs from HOME only...
Enough?

**Comment by Alir3z4** [comment]
Yep, that's great.
Thanks ;)
